### ISSUE TITLE
`df_to_table()` does not fail elegantly when the table already exists.

### ISSUE THREAD

**Issue by robfraz** [robfraz/gbq-pandas#1]
The traceback is pretty oblique:

```
Traceback (most recent call last):
  File "/Users/rob/code/gbq-pandas/venv/lib/python3.6/site-packages/google/cloud/bigquery/table.py", line 1150, in upload_from_file
    client, file_obj, metadata, size, num_retries)
  File "/Users/rob/code/ovo/gbq-pandas/venv/lib/python3.6/site-packages/google/cloud/bigquery/table.py", line 1025, in _do_upload
    client, stream, metadata, num_retries)
  File "/Users/rob/code/gbq-pandas/venv/lib/python3.6/site-packages/google/cloud/bigquery/table.py", line 938, in _do_resumable_upload
    client, stream, metadata, num_retries)
  File "/Users/rob/code/gbq-pandas/venv/lib/python3.6/site-packages/google/cloud/bigquery/table.py", line 913, in _initiate_resumable_upload
    stream_final=False)
  File "/Users/rob/code/gbq-pandas/venv/lib/python3.6/site-packages/google/resumable_media/requests/upload.py", line 327, in initiate
    self._process_initiate_response(result)
  File "/Users/rob/code/gbq-pandas/venv/lib/python3.6/site-packages/google/resumable_media/_upload.py", line 449, in _process_initiate_response
    response, u'location', self._get_headers)
  File "/Users/rob/code/gbq-pandas/venv/lib/python3.6/site-packages/google/resumable_media/_helpers.py", line 64, in header_required
    response, u'Response headers must contain header', name)
google.resumable_media.common.InvalidResponse: ('Response headers must contain header', 'location')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "examples.py", line 42, in <module>
    main()
  File "examples.py", line 27, in main
    gbq.df_to_table(df1, table)
  File "/Users/rob/code/gbq-pandas/gbq_pandas.py", line 44, in df_to_table
    write_disposition=write_disposition)
  File "/Users/rob/code/gbq-pandas/venv/lib/python3.6/site-packages/google/cloud/bigquery/table.py", line 1153, in upload_from_file
    raise exceptions.from_http_response(exc.response)
google.api.core.exceptions.NotFound: 404 POST https://www.googleapis.com/upload/bigquery/v2/projects/trading-nonprod/jobs?uploadType=resumable: Not found: Job trading-nonprod:job_lJSubTOw_ftCBxvVMruzkxZZGo2M
```

**Comment by robfraz** [comment]
Either my initial bug report was erroneous, or this has been improved on the google side of things.  It now returns a 409 conflict, which is correct:

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "examples.py", line 42, in <module>
    main()
  File "examples.py", line 27, in main
    gbq.df_to_table(df1, table)
  File "/Users/rob/code/gbq-pandas/gbq_pandas.py", line 55, in df_to_table
    write_disposition=write_disposition)
  File "/Users/rob/code/gbq-pandas/venv/lib/python3.6/site-packages/google/cloud/bigquery/table.py", line 1153, in upload_from_file
    raise exceptions.from_http_response(exc.response)
google.api.core.exceptions.Conflict: 409 POST https://www.googleapis.com/upload/bigquery/v2/projects/trading-nonprod/jobs?uploadType=resumable: Already Exists: Table trading-nonprod:robfraz_sandbox.example_table_1
```
